using Examination_System.Models.Enum;
using System.ComponentModel.DataAnnotations;

namespace Examination_System.Models
{
    public class Exam : BaseModel<Guid>
    {
        [Required]
        [StringLength(100)]
        public string Title { get; set; } = null!;
        public ExamType Type { get; set; }
        public int NumberOfQuestions { get; set; }
        public bool IsAutoGenerated { get; set; }
        public Guid CourseId { get; set; }
        public Course Course { get; set; } = null!;
        public ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();
        public ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    }
}
